sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t wenbo0925/react-dock -f Dockerfile.dev .

script:
    - docker run -e CI=true wenbo0925/react-dock npm run test

deploy:
    provider: elasticbeanstalk
    region: "ca-central-1"
    app: "docker-react-test"
    env: "DockerReactTest-env"
    bucket_name: "elasticbeanstalk-ca-central-1-562819747386"
    bucket_path: "docker-react-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
