sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t wenbo0925/react-dock -f Dockerfile.dev .

script:
    - docker run -e CI=true wenbo0925/docker-react npm run test